wandb_version: 1

Architecture:
  desc: null
  value: u2net_lite
_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1681495552.90413
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.13.6
      8:
      - 4
      - 5
trainer:
  desc: null
  value: Trainer
