name: ISNetDIS_scratch_1gpu-bs4_KNC_size1024x1024

n_gpu: 1

arch:
  type: ISNetDIS
  args: {}

gte:
  interm_supervision: True

  seed: 0
  gt_encoder_model: ""

  model_path: "saved_gte/"
  model_save_fre: 2000
  max_ite: 10000000

  batch_size_train: 1
  batch_size_valid: 1

  start_ite: 0 
  max_epoch_num: 10

  early_stop: 20

data_loader:
  type: KNCDataLoader
  args:

    batch_size: 12 # 32 for training gte
    shuffle: true
    num_workers: 4
    validation_split: 0.1
    output_size: 400
    crop_size: 384

    dir: "data_demo" # "../split_dataset/train"

optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    eps: 1.e-8
    betas:
      - 0.9
      - 0.999

loss: multi_mse_fusion

metrics:
  - mae
  - sm

lr_scheduler:
  type: CosineAnnealingLR
  args:
    T_max: 14000
    eta_min: 0.000001

trainer:
  type: Trainer

  epochs: 10
  save_dir: saved/
  save_period: 1
  verbosity: 1

  visual_tool: wandb
  project: cvps23

  # Edit *username for tracking WandB multi-accounts
  api_key_file: ./configs/api/tuanlda78202
  entity: tuanlda78202
  
test:
  save_dir: saved/generated
  n_sample: 1000
  batch_size: 32

# DIS Configuration


# Model Directories 
dir:
  start_ite: 0 
  model_path: "../saved_models/IS-Net-test"   ## model weights saving (or restoring) path
  gt_encoder_model:                           # part of GTEncoder


# Floating point accuracy
accurary:
  model_digit: "full"   # indicates "half" or "full" accuracy of float number
  seed: 0


# Cache data spatial size
# To handle large size input images, which take a lot of time for loading in training,
# introduce cache mechanism for pre-convering and resizing the jpg and png images into .pt file
cache:
  cache_size: [1024, 1024]  # cached input spatial resolution

  # Indicates wheather to load all the training datasets into RAM
  # True will greatly speed the training process while requires more RAM
  cache_boost_train: False 
  cache_boost_valid: False 


# Data augmentation parameters
augmentation:
  input_size: [1024, 1024]  # model input spatial size, usually use the same value hypar["cache_size"], which means we don't further resize the images
  crop_size: [920, 920]     # random crop size from the input, it is usually set as smaller than hypar["cache_size"], e.g., [920,920] for data augmentation
  flip_hor: 1               # horizontal flip, currently hard coded in the dataloader and it is not in use
  random_flip_ver: 0        # vertical flip , currently not in use


# Saving 
saving: 
  model_save_freq: 2000
  early_stop: 20          # stop the training when no improvement in the past 20 validation periods
  max_iter: 10000000      # if early stop couldn't stop the training process, stop it by the max_ite_num
  max_epoch_num: 1000000  # if early stop and max_ite couldn't stop the training process, stop it by the max_epoch_num


# Inference 
inference:
  dataset_path: "../data_infer/knc" 
  model_path: "../saved_models/IS-Net/isnet-general-use.pth"
  result_path:  "../data_infer/knc_result"
  input_size: [1024,1024]


