name: U2NetFull_scratch_1gpu-bs4_KNC_size320x320

n_gpu: 1

arch:
  type: u2net_full
  args: {}

data_loader:
  type: KNCDataLoader
  args:
    batch_size: 4
    shuffle: true
    num_workers: 4
    validation_split: 0.1
    output_size: 400
    crop_size: 384
    dir: "data_demo" # "../split_dataset/train"

optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    eps: 1.e-8
    betas:
      - 0.9
      - 0.999

loss: multi_bce_fusion

metrics:
  - mae
  - sm
  # - maxfm
  # - wfm

lr_scheduler:
  type: CosineAnnealingLR
  args:
    T_max: 14000
    eta_min: 0.000001

trainer:
  type: Trainer

  epochs: 10
  save_dir: saved/
  save_period: 1
  verbosity: 1

  visual_tool: wandb
  project: cvps23

  # Edit *username for tracking WandB multi-accounts
  api_key_file: ./configs/api/tuanlda78202
  entity: tuanlda78202
  
test:
  save_dir: saved/generated
  n_sample: 1000
  batch_size: 32
