wandb_version: 1

Architecture:
  desc: null
  value: u2net_lite
trainer:
  desc: null
  value: Trainer
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688807051.77853
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.1
      8:
      - 5
